name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache node_modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: node_modules
          key: project-npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            project-npm-${{ runner.os }}-

      - name: Install dependencies
        run: |
          if [ "${{ steps.cache-npm.outputs.cache-hit }}" != "true" ]; then
            npm ci || (npm install && npm cache clean --force)
          fi

      - name: Save cache
        if: steps.cache-npm.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: node_modules
          key: project-npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Build project
        run: npm run build

      - name: Verify build output
        run: |
          if [[ ! -d "dist" ]]; then
            echo "Error: Build output directory 'dist' not found."
            exit 1
          fi
          if [[ ! -f "dist/404.html" ]]; then
            echo "Error: 404.html not found in dist folder."
            exit 1
          fi
          if [[ ! -f "dist/index.html" ]]; then
            echo "Error: index.html not found in dist folder."
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
          cname: hemanthscode.github.io

      - name: Notify on failure
        if: failure()
        run: echo "🚨 Deployment to GitHub Pages failed. Check workflow logs at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"